### ISSUE TITLE
Newly added child sites with WSAL are not being recognized in the activity log

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#19]
The MainWP install on https://mainwp.wpwhitesecurity.net/ has 2 child sites by default.

I installed the activity log and all worked well. Though I:

1) Added https://mainwpsub3.wpwhitesecurity.net/ as a child site after
2) Installed WSAL from MainWP
3) Whenever I refresh the list of sites in the plugin settings the new sub3 site is not being recognized when I click **Refresh Child Sites**

![image](https://user-images.githubusercontent.com/9016202/47355720-ff944100-d6b9-11e8-9fc1-a0e19f5ce101.png)

I also tried several times syncing data with child sites, creating events in the activity log etc, but none are working.

**Comment by asharirfan** [comment]
@WPWhiteSecurity 

> Installed WSAL from MainWP

The code for supporting MainWP extension in WSAL has not been merged to master and released to wp.org repository yet. 

You need to install the version from this [branch](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/tree/mainwp-ext) for now.
