### ISSUE TITLE
Add MainWP styled plugin logo to extension

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#25]
Please use this plugin logo instead.
[MainWP extension.zip](https://github.com/WPWhiteSecurity/activity-log-mainwp/files/2524777/MainWP.extension.zip)

**Comment by asharirfan** [comment]
@WPWhiteSecurity Closing this issue since we are currently using this logo.

### Screenshot:
![alt text](https://cl.ly/0164e18dc960/💯 "Sample alt")
