### ISSUE TITLE
Better handle extension install with no WSAL child sites

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#27]
When no child sites have WSAL installed, in the wizard the users see this:

![image](https://user-images.githubusercontent.com/9016202/48630109-4de3e980-e9b3-11e8-991a-4c1a07895ecc.png) Let's show a message instead:

It seems that the WP Security Audit Log plugin is not installed on any of the child sites. Please exit this wizard, install the WP Security Audit Log plugin on the child sites and then add the sites from the Extensions settings. Refer to the [Getting Started Guide](https://www.wpsecurityauditlog.com/support-documentation/gettting-started-activity-log-mainwp-extension/) for more information.

Also change the plugin from **Finish** to **Exit Wizard** in such case.

_Exception:_  It seems that in some cases the wizard does not even load as per the below screenshot. Speak to Bogdan from MainWP for more information on how to reproduce this:

![image](https://user-images.githubusercontent.com/9016202/48630295-d5c9f380-e9b3-11e8-922b-e88f4b1bbdb9.png)

**Comment by asharirfan** [comment]
@WPWhiteSecurity 

> Exception: It seems that in some cases the wizard does not even load as per the below screenshot. Speak to Bogdan from MainWP for more information on how to reproduce this:
![image](https://user-images.githubusercontent.com/9016202/48630295-d5c9f380-e9b3-11e8-922b-e88f4b1bbdb9.png)

I have added a check to not display anything if there are no WSAL sites so this will not occur again.
