### ISSUE TITLE
Handle error when installing extension on WordPress without MainWP

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#28]
By mistake some people installed the extension on the child sites instead of the Dashboard and got a HTTP 500 Internal server error.

We should handle this better - if the extension is installed on a site without MainWP, upon activation we should show a pop up -

This extension should be installed on the MainWP dashboard site. On the child sites please install the WP Security Audit Log plugin. Refer to the [Getting Started Guide](https://www.wpsecurityauditlog.com/support-documentation/gettting-started-activity-log-mainwp-extension/) for more information.

[OK - Deactivate Plugin]

Once the user clicks Ok automatically deactivate the extension.

**Comment by asharirfan** [comment]
@WPWhiteSecurity 

Is following notice okay? This is what we use in WSAL when the PHP version is lesser than the required limit.

![image](https://cl.ly/95958ee6fa0e/💯)

We won't be able to add a fancy popup since we can't include JS library at this point.

**Comment by WPWhiteSecurity** [comment]
Sure let's use this.

**Comment by asharirfan** [comment]
![image](https://cl.ly/701c34392f1e/💯)
