### ISSUE TITLE
Sites drop down menu in Activity Log view and too many sites

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#30]
Did we implement any sort of restriction on the site drop down menu for when there are many sites?

![image](https://user-images.githubusercontent.com/9016202/49999086-3be76d80-ff96-11e8-94d1-004666d7b833.png)

If not we should have the following, as it is for our multisite:

1. Up to 20 sites we should show the drop down menu
2. More than 20 we should have like a search box with auto suggestion. Otherwise it will be a problem to display 100 or more websites in the menu.

**Comment by asharirfan** [comment]
@WPWhiteSecurity Or we can implement a select2 box like the following one. It will be able to manage a large number of websites with search support.

![image](https://cl.ly/28c1dd95ea68/💯)
