### ISSUE TITLE
Incorrect order of reporting events

### ISSUE THREAD

**Issue by WPWhiteSecurity** [WPWhiteSecurity/activity-log-mainwp#32]
When I run a retrieval of events event 7711 is reported after the new imported events:

![image](https://user-images.githubusercontent.com/9016202/50683671-20123d00-1013-11e9-9201-770127979cff.png)

This process and reporting of events should be different:

1) Start retrieval
2) Report event 7711
3) Import events
4) When all is ready report event 7712

**Comment by asharirfan** [comment]
@WPWhiteSecurity The events retrieval process is independent of this events order because the events could have older timestamps than 7711.

Check the following screenshot:

![image](https://cl.ly/e208c2ddc25c/💯)
