### ISSUE TITLE
Loading animation always present in List View

### ISSUE THREAD

**Issue by DannyWPWS** [WPWhiteSecurity/activity-log-mainwp#56]
The loading animation as seen here https://i.gyazo.com/0bcc79e35f055daacae7a00f556b8bd8.png is always present, even once everything is loaded in list view, in grid view an "end of activity log" message is shown instead

**Comment by DannyWPWS** [comment]
Actually, this only seems to happen if your displaying not enough log entries to fill your screen vertically (5 or less for example)

**Comment by martinkrcho** [comment]
@DannyWPWS , I think this one is already fixed.
