### ISSUE TITLE
Child sites settings not propogated to WSAL 4.1.5

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/activity-log-mainwp#89]
The chid site settings cannot be propogated from MainWP to child site with WSAL 4.1.5:

![image](https://user-images.githubusercontent.com/3965050/97444291-44e44c80-192c-11eb-8173-ef14324fcdff.png)

I think this might be related, but I logged in again tot he site later and this event is reported much later:

![image](https://user-images.githubusercontent.com/3965050/97444474-7ceb8f80-192c-11eb-8513-0fe0fb01f150.png)

**Comment by martinkrcho** [comment]
I will investigate on the "plugin not found" issue.

The delay in the second picture is OK. The settings are propagated using background processes. They can create alerts a bit later since communication with a number of child sites is involved.

**Comment by martinkrcho** [comment]
@robert81 , is it possible you did the following?

1. Add site MainWP3 to MainWP
2. Install WP Activity Log on MainWP3 child site
3. Change settings to be propagated
4. See the error message in log

When propagating the settings we check the plugin presence on a child site and a version number against the MainWP database. That is what we have available. I think it did not have a fresh list of plugins from child site when you tried to propagated the settings.

I synced the dashboard with the child sites and it worked fine now. Well, it reported that MainWP1 and MainWP2 have the wrong WSAL version now, but that is expected.

**Comment by robert81** [comment]
Now that's another big 🤦 for me today! 

I installed the plugin on MainWP3 directly without synching.. so I added the site but as such MainWP was not aware of the plugin. Good point. All is working well here :)
